### ISSUE TITLE
JacksonUtil not working in version 0.62

### ISSUE THREAD

**Issue by marcocast** [aol/micro-server#54]
The previous com.aol.micro.server.rest.JacksonUtil has been replaced by com.aol.micro.server.rest.jackson.JacksonUtil, but when running a simple json conversion (working with 0.59) I get the following error : 

java.lang.NoClassDefFoundError: com/aol/cyclops/lambda/monads/SequenceM
	at com.aol.micro.server.PluginLoader.load(PluginLoader.java:21)
	at com.aol.micro.server.PluginLoader$$Lambda$1/1282287470.get(Unknown Source)
	at com.aol.cyclops.lambda.utils.LazyImmutable.setOnceFromSupplier(LazyImmutable.java:116)
	at com.aol.cyclops.lambda.utils.LazyImmutable.computeIfAbsent(LazyImmutable.java:133)
	at com.aol.cyclops.functions.Memoise.lambda$memoiseSupplier$109(Memoise.java:27)
	at com.aol.cyclops.functions.Memoise$$Lambda$2/2104028992.get(Unknown Source)
	at com.aol.micro.server.rest.jackson.JacksonUtil.getMapper(JacksonUtil.java:39)
	at com.aol.micro.server.rest.jackson.JacksonUtil.serializeToJson(JacksonUtil.java:63)
	at com.ucd.geoservices.model.QueryRadiusRequestTest.testJson(QueryRadiusRequestTest.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: java.lang.ClassNotFoundException: com.aol.cyclops.lambda.monads.SequenceM
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 32 more

Is cyclops already part of the micro-server-core?

**Comment by johnmcclean-aol** [comment]
Hey Marco,

Yes it is. I suspect this error is related to this one as it appears to be
happening during plugin loading :
https://github.com/aol/micro-server/issues/52

The gradle Shadow Jar implementation overwrites files in META-INF/services
directory each time when building a fat jar (and Cyclops and Microserver
use this folder to store plugin definitions). You can fix it with

shadowJar { mergeServiceFiles() }

If you're using a different Fat Jar implementation - or this doesn't fix
the issue do let me know!

Thanks,
John


On Wed, Aug 12, 2015 at 8:36 AM, Marco Castigliego <notifications@github.com

**Comment by marcocast** [comment]
Hey John,

I'm actually using maven, and I'm not building a fat jar, but simply running some unit tests through eclipse (mvn clean install has the same error). 
I cleaned a bit my dependencies, but still failing, now I'm getting : 

java.lang.IncompatibleClassChangeError: Class com.aol.cyclops.lambda.monads.MonadWrapper does not implement the requested interface com.aol.cyclops.internal.Monad
	at com.aol.cyclops.lambda.monads.SequenceM.filter(SequenceM.java:1412)
	at com.aol.micro.server.rest.jackson.JacksonUtil.getMapper(JacksonUtil.java:40)
	at com.aol.micro.server.rest.jackson.JacksonUtil.serializeToJson(JacksonUtil.java:63)
	at com.ucd.geoservices.model.QueryRadiusRequestTest.testJson(QueryRadiusRequestTest.java:36)
	......

**Comment by johnmcclean-aol** [comment]
That looks at a dependency issue. The simple-react POM imports cyclops
4.0.3 in test scope. With Gradle this get's ignored, but possibly Maven
pulls it in? (In which case would have to go back and look at the
simple-react build). Can you check to see if multiple versions of Cyclops
are on the classpath?

<dependency>
<groupId>com.aol.cyclops</groupId>
<artifactId>cyclops-core</artifactId>
<version>4.0.3</version>
<scope>test</scope>
</dependency>

On Wed, Aug 12, 2015 at 9:58 AM, Marco Castigliego <notifications@github.com

**Comment by marcocast** [comment]
It was a dependencies issue indeed, but on my local machine. 
Fixed by cleaning completely all my m2 repository. 

There is a single version of Cyclops (5.1.0) in the classpath now, 


Thanks John, have a good day!

Marco
